### ISSUE TITLE
Codm detection

### ISSUE THREAD

**Issue by lerKingtedy** [Xposed-Modules-Repo/io.github.rushiranpise.gameunlocker#1]
Update 3.0 gets banned after a few ranked matches for usual environment.
![Screenshot_2023-11-12-11-35-20-924_com activision callofduty shooter](https://github.com/Xposed-Modules-Repo/io.github.rushiranpise.gameunlocker/assets/150621306/897fb19c-da44-45f1-88f2-bd021fbe391b)

**Comment by rushiranpise** [comment]
1. Try clearing game data and check
2. Downgrade to 2.0 and check

**Comment by lerKingtedy** [comment]
1.0 works perfectly. Haven't checked 2.0

**Comment by rushiranpise** [comment]
ttry this,
install 4.0.0,
force stop game & clear game data
open game
